# Generated by Django 5.2.7 on 2025-10-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('rpm', models.FloatField()),
                ('torque', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MalfunctionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message_type', models.CharField(choices=[('INFO', 'Meldung'), ('WARNING', 'Warnung'), ('ERROR', 'Störung')], max_length=10)),
                ('description', models.TextField()),
                ('motor_state', models.CharField(max_length=50)),
                ('emergency_stop_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MotorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('identification', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('commissioning_date', models.DateField(blank=True, null=True)),
                ('cycles', models.PositiveIntegerField(default=0)),
                ('operating_mode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
                ('rpm', models.FloatField()),
                ('torque', models.FloatField(blank=True, null=True)),
                ('run_time', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
