# Generated by Django 5.2.7 on 2025-10-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Erwarteter Strom (A)')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Erwartete Spannung (V)')),
                ('rpm', models.FloatField(blank=True, null=True, verbose_name='Erwartete Drehzahl (RPM)')),
                ('torque', models.FloatField(blank=True, null=True, verbose_name='Erwartetes Drehmoment (Nm)')),
                ('run_time', models.FloatField(blank=True, null=True, verbose_name='Erwartete Laufzeit (h)')),
            ],
            options={
                'verbose_name': 'Twin-Daten',
                'verbose_name_plural': 'Twin-Daten',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='livedata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Live-Daten', 'verbose_name_plural': 'Live-Daten'},
        ),
        migrations.AlterModelOptions(
            name='malfunctionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Störmeldung', 'verbose_name_plural': 'Störmeldungen'},
        ),
        migrations.AlterModelOptions(
            name='motorinfo',
            options={'verbose_name': 'Motorinformation', 'verbose_name_plural': 'Motorinformationen'},
        ),
        migrations.AlterModelOptions(
            name='referencerun',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Referenzlauf', 'verbose_name_plural': 'Referenzläufe'},
        ),
        migrations.AlterField(
            model_name='livedata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Strom (A)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='rpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Drehzahl (RPM)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Laufzeit (h)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Drehmoment (Nm)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Spannung (V)'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='emergency_stop_active',
            field=models.BooleanField(default=False, verbose_name='Not-Aus aktiv'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='message_type',
            field=models.CharField(choices=[('INFO', 'Meldung'), ('WARNING', 'Warnung'), ('ERROR', 'Störung')], max_length=10, verbose_name='Nachrichtentyp'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='motor_state',
            field=models.CharField(max_length=50, verbose_name='Motorzustand'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Inbetriebnahme'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='cycles',
            field=models.PositiveIntegerField(default=0, verbose_name='Betriebszyklen'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='identification',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kennzeichnung'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Ort'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Modell'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Motor Name'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='operating_mode',
            field=models.CharField(max_length=50, verbose_name='Betriebsmodus'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Strom (A)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Ist gültig'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Referenzlauf Name'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='rpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Drehzahl (RPM)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Laufzeit (h)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zeitstempel'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Drehmoment (Nm)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Spannung (V)'),
        ),
    ]
