# Generated by Django 5.2.7 on 2025-10-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0002_twindata_alter_livedata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livedata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatur (°C)'),
        ),
        migrations.AddField(
            model_name='livedata',
            name='vibration',
            field=models.FloatField(blank=True, null=True, verbose_name='Vibration (mm/s)'),
        ),
        migrations.AddField(
            model_name='referencerun',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperatur (°C)'),
        ),
        migrations.AddField(
            model_name='referencerun',
            name='vibration',
            field=models.FloatField(blank=True, null=True, verbose_name='Vibration (mm/s)'),
        ),
        migrations.AddField(
            model_name='twindata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Erwartete Temperatur (°C)'),
        ),
        migrations.AddField(
            model_name='twindata',
            name='vibration',
            field=models.FloatField(blank=True, null=True, verbose_name='Erwartete Vibration (mm/s)'),
        ),
    ]
