# Generated by Django 5.2.10 on 2026-01-20 20:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot_app', '0003_livedata_temp_livedata_vibration_referencerun_temp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livedata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Live Data', 'verbose_name_plural': 'Live Data'},
        ),
        migrations.AlterModelOptions(
            name='malfunctionlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Malfunction Log', 'verbose_name_plural': 'Malfunction Logs'},
        ),
        migrations.AlterModelOptions(
            name='motorinfo',
            options={'verbose_name': 'Motor Information', 'verbose_name_plural': 'Motor Information'},
        ),
        migrations.AlterModelOptions(
            name='referencerun',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Reference Run', 'verbose_name_plural': 'Reference Runs'},
        ),
        migrations.AlterModelOptions(
            name='twindata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Twin Data', 'verbose_name_plural': 'Twin Data'},
        ),
        migrations.AlterField(
            model_name='livedata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Current (A)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='rpm',
            field=models.FloatField(blank=True, null=True, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Run Time (h)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Torque (Nm)'),
        ),
        migrations.AlterField(
            model_name='livedata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Voltage (V)'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='emergency_stop_active',
            field=models.BooleanField(default=False, verbose_name='Emergency Stop Active'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='message_type',
            field=models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=10, verbose_name='Message Type'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='motor_state',
            field=models.CharField(max_length=50, verbose_name='Motor State'),
        ),
        migrations.AlterField(
            model_name='malfunctionlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='commissioning_date',
            field=models.DateField(blank=True, null=True, verbose_name='Commissioning Date'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='cycles',
            field=models.PositiveIntegerField(default=0, verbose_name='Operating Cycles'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='identification',
            field=models.CharField(max_length=100, unique=True, verbose_name='Identification'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='motorinfo',
            name='operating_mode',
            field=models.CharField(max_length=50, verbose_name='Operating Mode'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Current (A)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Is Valid'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Reference Run Name'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='rpm',
            field=models.FloatField(blank=True, null=True, verbose_name='RPM'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Run Time (h)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Torque (Nm)'),
        ),
        migrations.AlterField(
            model_name='referencerun',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Voltage (V)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='current',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Current (A)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='rpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected RPM'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='run_time',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Run Time (h)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='torque',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Torque (Nm)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='vibration',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Vibration (mm/s)'),
        ),
        migrations.AlterField(
            model_name='twindata',
            name='voltage',
            field=models.FloatField(blank=True, null=True, verbose_name='Expected Voltage (V)'),
        ),
        migrations.CreateModel(
            name='FeatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitstempel')),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperatur'), ('current', 'Strom'), ('torque', 'Drehmoment')], max_length=50, verbose_name='Metrik-Typ')),
                ('mean', models.FloatField(blank=True, null=True, verbose_name='Mittelwert')),
                ('min_val', models.FloatField(blank=True, null=True, verbose_name='Minimum')),
                ('max_val', models.FloatField(blank=True, null=True, verbose_name='Maximum')),
                ('median', models.FloatField(blank=True, null=True, verbose_name='Median')),
                ('std_dev', models.FloatField(blank=True, null=True, verbose_name='Standardabweichung')),
                ('data_range', models.FloatField(blank=True, null=True, verbose_name='Bereich (Range)')),
            ],
            options={
                'verbose_name': 'Feature-Daten',
                'verbose_name_plural': 'Feature-Daten',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='iot_app_fea_metric__049993_idx')],
            },
        ),
        migrations.CreateModel(
            name='PredictionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitstempel')),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperatur'), ('current', 'Strom'), ('torque', 'Drehmoment')], max_length=50, verbose_name='Metrik-Typ')),
                ('predicted_value', models.FloatField(blank=True, null=True, verbose_name='Vorhergesagter Wert')),
                ('anomaly_score', models.FloatField(blank=True, null=True, verbose_name='Anomalie-Score')),
                ('rul_hours', models.FloatField(blank=True, null=True, verbose_name='Restnutzungsdauer (h)')),
            ],
            options={
                'verbose_name': 'Vorhersagedaten',
                'verbose_name_plural': 'Vorhersagedaten',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='iot_app_pre_metric__90d3a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zeitstempel')),
                ('metric_type', models.CharField(choices=[('temperature', 'Temperatur'), ('current', 'Strom'), ('torque', 'Drehmoment')], max_length=50, verbose_name='Metrik-Typ')),
                ('value', models.FloatField(verbose_name='Wert')),
            ],
            options={
                'verbose_name': 'Rohdaten',
                'verbose_name_plural': 'Rohdaten',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['metric_type', 'timestamp'], name='iot_app_raw_metric__8a26f8_idx')],
            },
        ),
    ]
